#!/bin/bash


# Color Definitions
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'

BOLD_GRAY='\033[0;37m'
BOLD_RED='\033[1;31m'
BOLD_GREEN='\033[1;32m'
BOLD_BLUE='\033[1;34m'
BOLD_PURPLE='\033[1;35m'
BOLD_CYAN='\033[1;36m'

DARK_GRAY='\033[1;30m'
WHITE='\033[1;37m'
NC='\033[0m'

BOLD=$(tput bold)
NORMAL=$(tput sgr0)


# Clear the screen.
clear


# Build Steps
echo -e "${YELLOW}${BOLD}[ Starting Build for FrontEnd ]${NORMAL}"
cd frontend
npm run build
echo -e "${YELLOW}${BOLD}[ Build Finished for FrontEnd ]${NORMAL}"
echo ""

echo -e "${BLUE}${BOLD}[ Build Finished for Backend ]${NORMAL}"
cd ../backend
pwd
echo -e "${BLUE}${BOLD}[ Build Finished for Backend ]${NORMAL}"
echo ""

# exiting
exit 0

# echo -e "${BOLD}Color Test${NORMAL}"

# echo ""

# echo -e "Black: ${BLACK}Lorem Ipsum ${NC}"

# echo -e "Red: ${RED}Lorem Ipsum ${NC}"

# echo -e "Green: ${GREEN}Lorem Ipsum ${NC}"

# echo -e "Blue: ${BLUE}Lorem Ipsum ${NC}"

# echo -e "Purple: ${PURPLE}Lorem Ipsum ${NC}"

# echo -e "Cyan: ${CYAN}Lorem Ipsum ${NC}"

# echo -e "Yellow: ${YELLOW}Lorem Ipsum ${NC}"